# Reference: https://docs.gitlab.com/ee/ci/yaml/README.html
# Linter: https://gitlab.com/mburolla/serverless-ci-deploy/-/ci/lint

stages: 
 - deploy 

################################################################################
# STAGING                                                                      #
################################################################################

# deploy_stage: 
#   stage: deploy  
#   image: node:latest
#   only:
#     - stage 
#   before_script:
#     - npm config set prefix /usr/local
#     - npm install -g serverless
#     - serverless-plugin-typescript
#     - npm install
#     - apt-get update
#     - apt-get -y install python3-pip
#     - pip3 install awscli --upgrade --user
#   script:     
#     - ~/.local/bin/aws s3 cp s3://sls-config/stage.json ./config/stage.json
#     - serverless deploy --verbose
#   environment: stage

# test_stage:
#   stage: test  
#   image: node:latest
#   only:
#     - stage 
#   before_script:
#     - npm install
#   script:     
#     - npm test
#   environment: stage

################################################################################
# PRODUCTION                                                                   #
################################################################################

deploy_dev: 
  stage: deploy  
  image: node:.
  only:
    - dev 
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - serverless-plugin-typescript  
    - npm install
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install awscli --upgrade --user
  script:   
    - serverless deploy --stage dev --verbose 
  environment: dev
